language: julia

os:
  - osx

branches:
  only:
  - master

julia:
  - 1.4

notifications:
  email: false

install:
 - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/cvdlab/LinearAlgebraicRepresentation.jl"))';
 - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/marteresagh/Common.jl"))';
 - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/marteresagh/FileManager.jl."))';

after_success:
 - julia -e 'using Pkg; cd(Pkg.dir("OrthographicProjection")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())';
 - julia -e 'using Pkg; Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))';


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
