language: julia
os:
  - osx
julia:
  - 1.4
branches:
  only:
    - master
notifications:
  email: false
jobs:
  include:
    - stage: "Documentation"
      julia: 1.4
      os: osx
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip
