language: julia

os:
  - osx

branches:
  only:
  - master

julia:
  - 1.4

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter"); Pkg.add("Coverage");'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.4
      os: osx
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip
